model:
  name: "DyRep"
  hidden_dim: 128
  time_dim: 16
  type_embedding_dim: 16
  dropout: 0.2

training:
  device: "cuda"

  batch_size: 8192
  eval_batch_size: 16384

  lr: 0.0005
  weight_decay: 0.0001

  epochs: 1                  # KEEP THIS
  early_stopping_patience: 1  # BEST VALUE FOR DYREP

  optimizer:
    type: "adam"
    betas: [0.9, 0.999]
    eps: 1e-8

loss:
  type: "bce"
  pos_weight: null
